// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: service.account.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestGetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterId int32 `protobuf:"varint,1,opt,name=filter_id,json=filterId,proto3" json:"filter_id,omitempty"`
}

func (x *RequestGetAccount) Reset() {
	*x = RequestGetAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetAccount) ProtoMessage() {}

func (x *RequestGetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetAccount.ProtoReflect.Descriptor instead.
func (*RequestGetAccount) Descriptor() ([]byte, []int) {
	return file_service_account_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetAccount) GetFilterId() int32 {
	if x != nil {
		return x.FilterId
	}
	return 0
}

type ResponseGetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance float32 `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *ResponseGetAccount) Reset() {
	*x = ResponseGetAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetAccount) ProtoMessage() {}

func (x *ResponseGetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_service_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetAccount.ProtoReflect.Descriptor instead.
func (*ResponseGetAccount) Descriptor() ([]byte, []int) {
	return file_service_account_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseGetAccount) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseGetAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResponseGetAccount) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_service_account_proto protoreflect.FileDescriptor

var file_service_account_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x12, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32, 0x69,
	0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x57, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_account_proto_rawDescOnce sync.Once
	file_service_account_proto_rawDescData = file_service_account_proto_rawDesc
)

func file_service_account_proto_rawDescGZIP() []byte {
	file_service_account_proto_rawDescOnce.Do(func() {
		file_service_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_account_proto_rawDescData)
	})
	return file_service_account_proto_rawDescData
}

var file_service_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_account_proto_goTypes = []interface{}{
	(*RequestGetAccount)(nil),  // 0: service_account.RequestGetAccount
	(*ResponseGetAccount)(nil), // 1: service_account.ResponseGetAccount
}
var file_service_account_proto_depIdxs = []int32{
	0, // 0: service_account.AccountService.GetAccount:input_type -> service_account.RequestGetAccount
	1, // 1: service_account.AccountService.GetAccount:output_type -> service_account.ResponseGetAccount
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_account_proto_init() }
func file_service_account_proto_init() {
	if File_service_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_account_proto_goTypes,
		DependencyIndexes: file_service_account_proto_depIdxs,
		MessageInfos:      file_service_account_proto_msgTypes,
	}.Build()
	File_service_account_proto = out.File
	file_service_account_proto_rawDesc = nil
	file_service_account_proto_goTypes = nil
	file_service_account_proto_depIdxs = nil
}
